server:
  port: 8080
spring:
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true