server:
  port: 8084
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloudsleuth
    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true